services:
    backend:
      build: ./backend
      ports:
        - "3000:3000"
    
    frontend:
      build: ./frontend
      ports:
        - "8080:3000"
      depends_on:
        - backend

    db:
      image: memcached:latest
      ports:
        - "11211:11211"